repos:
- repo: https://github.com/charliermarsh/ruff-pre-commit
    # Ruff version.
  rev: v0.0.254
  hooks:
  - id: ruff
    args: [--fix, --exit-non-zero-on-fix]
- repo: https://github.com/psf/black
  rev: 22.3.0
  hooks:
  - id: black
    language_version: python3
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.3.0
  hooks:
  - id: check-merge-conflict
  - id: mixed-line-ending
- repo: https://github.com/Lucas-C/pre-commit-hooks-safety
  rev: v1.3.1
  hooks:
  - id: python-safety-dependencies-check

- repo: https://github.com/hadolint/hadolint
  rev: v2.12.0
  hooks:
  - id: hadolint-docker
    name: Lint Dockerfiles (Docker image)
    description: Runs hadolint Docker image to lint Dockerfiles
    language: docker_image
    types: [dockerfile]
    entry: ghcr.io/hadolint/hadolint hadolint

- repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
  rev: v2.13.0
  hooks:
  - id: pretty-format-yaml
    args: [--autofix, --indent, '2']
