services:
  keycloak-db:
    image: postgres:15-alpine
    ports:
    - 5432:5432
    environment:
      - POSTGRES_USER=dummy_pg_user
      - POSTGRES_PASSWORD=dummy_pg_pwd
      - POSTGRES_DB=keycloak
    healthcheck:
      test: [CMD-SHELL, sh -c 'pg_isready -U dummy_pg_user -d keycloak']
      interval: 20s
      timeout: 10s
      retries: 10
  keycloak:
    image: quay.io/keycloak/keycloak:26.5.2
    ports:
      - "9310:9310"
      - "8443:8443"
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: ${KEYCLOAK_USERNAME}
      KC_BOOTSTRAP_ADMIN_PASSWORD: ${KEYCLOAK_PASSWORD}
      KC_HTTP_PORT: 9310
      KC_HTTPS_PORT: 8443
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloak-db:5432/keycloak
      KC_DB_USERNAME: dummy_pg_user
      KC_DB_PASSWORD: dummy_pg_pwd
      KC_ENABLE_HTTPS: true
      KC_LOG_LEVEL: info
    volumes:
      - "./containers/keycloak/:/opt/bitnami/keycloak/data/import/"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://keycloak:9310" ]
      interval: 10s
      timeout: 5s
      retries: 3
    command: start --import-realm