FROM python:3.8.16-slim

RUN apt-get update
RUN apt-get install -y git
RUN pip install pandas git+https://github.com/pyronear/pyro-engine@develop

# Copy your initialization script into the container
COPY init_script.py /usr/local/bin/

# Set execute permission on the script
RUN chmod +x /usr/local/bin/init_script.py

# Command to run the script
CMD ["python /usr/local/bin/init_script.py"]